name: Build & Deploy to Azure Container App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to ACR
      - name: Log in to Azure Container Registry
        run: az acr login --name nishrepo

      # Build and push image
      - name: Build and Push Docker Image
        run: |
          docker build -t nishrepo.azurecr.io/bookfromhub:latest .
          docker push nishrepo.azurecr.io/bookfromhub:latest

      # Deploy to Azure Container App
      - name: Deploy to Azure Container App
        uses: azure/cli@v1
        with:
          azcliversion: 2.72.0
          inlineScript: |
            az containerapp update \
              --name BookFromHubApp \
              --resource-group Az-Certification \
              --image nishrepo.azurecr.io/bookfromhub:latest
