name: Build & Deploy Markdown-to-PDF Container

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/bookfromhub:latest

    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v4

      # 2️⃣ Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # use GHCR_PAT for private and  GITHUB_TOKEN for public repo

      # 3️⃣ Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"

      # 4️⃣ Log in to Azure (for deployment)
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

       # for container app, use this az containerapp update \
           #   --name BookHub \
            #  --resource-group Az-Certification \
            #  --image "$IMAGE_NAME"
      # 5️⃣ Deploy to Azure Container Instance
      - name: Deploy to Azure Container Instance
        uses: azure/cli@v1
        with:
          azcliversion: 2.72.0
          inlineScript: |
           az container create \
              --name bookhub \
              --resource-group Az-Certification \
              --image "$IMAGE_NAME" \
              --cpu 1 \
              --memory 1.5 \
              --os-type Linux \
              --restart-policy Always \
              --dns-name-label bookhub \
              --ports 80
          
